CREATE USER admin WITH PASSWORD '123456';
GRANT CONNECT ON DATABASE test_db TO admin;
GRANT USAGE ON SCHEMA public TO admin;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO admin;
    


CREATE USER operador WITH PASSWORD '456789';
GRANT CONNECT ON DATABASE test_db TO operador;
GRANT USAGE ON SCHEMA public TO operador;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO operador;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO operador;
